#!/bin/bash

set -e

BASE_IMAGE_NAME=ephemeral_mysql/base
BASE_DIR=/tmp/dokku-tmpmysql-dockerfile

rm -rf $BASE_DIR
git clone https://github.com/udzura/dokku-tmpmysql-dockerfile.git $BASE_DIR
docker build -q=true -t $BASE_IMAGE_NAME $BASE_DIR
rm -rf $BASE_DIR
echo "Installed ephemeral_mysql plugin."
